In [2]:
#START CODE HERE # (≈ 1 line of code)
sentence = "Hello World"
print(sentence)
### END CODE HERE ###

Hello World


In [3]:
# GRADED FUNCTION: basic_sigmoid
import math
def sigmoid(x):
    r = 1/(1+math.exp(-x))
    return r
    
#output for x=3:
print(sigmoid(3))    

0.9525741268224334


In [4]:
# One reason why we use "numpy" instead of "math" in Deep Learning #
# you will see this give an error when you run it, because x is a vector.#
x = [1, 2, 3]
sigmoid(x)

TypeError: bad operand type for unary -: 'list'

In [5]:
import numpy as np
#The property of distributability
x = np.array([1, 2, 3])
print(np.exp(x)) 

[ 2.71828183  7.3890561  20.08553692]


In [6]:
x = np.array([1, 2, 3])
print (x + 3)

[4 5 6]


In [10]:
def sigmoid_2(x):
#here we have np instead of math 
    s = 1/(np.exp(-x) + 1)
    return s
sigmoid_2(x)

array([0.73105858, 0.88079708, 0.95257413])

In [15]:
#Implement the function sigmoid_grad() to compute the gradient of the sigmoid function with respect to its input x. The formula is:
# GRADED FUNCTION: sigmoid_derivative
def derivative(x):
    s = sigmoid_2(x)
    ds = s*(1-s)
    return ds

x = np.array([1, 2, 3])    
print(derivative(x))

[0.19661193 0.10499359 0.04517666]


In [ ]:
#Implement the function sigmoid_grad() to compute the gradient of the sigmoid function with respect to its input x. The formula is:
# GRADED FUNCTION: sigmoid_derivative
def derivative(x):
    s = sigmoid_2(x)
    ds = s*(1-s)
    return ds

x = np.array([1, 2, 3])    
print(derivative(x))

[0.19661193 0.10499359 0.04517666]


In [17]:
# Implement image2vector() that takes an input of shape (length, height, 3) and returns a vector of shape (length*height*3, 1).
# For example, if you would like to reshape an array v of shape (a, b, c) into a vector of shape (a*b,c) you would do:
# v = v.reshape((v.shape[0]*v.shape[1], v.shape[2])) # v.shape[0] = a ; v.shape[1] = b ; v.shape[2] = c

def image2vector(image):
    v = image.reshape(image.shape[0]*image.shape[1]*image.shape[2],1)
    return v
image = np.array([[[ 1, 2],
        [ 3, 4],
        [ 5, 6]],

       [[ 7, 8],
        [ 9, 10],
        [ 11, 12]],

       [[ 13, 14],
        [ 15, 16],
        [ 17, 18]]])

print (image2vector(image))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]]


In [ ]:
# Implement normalizeRows() to normalize the rows of a matrix. After applying this function to an input matrix x,
# each row of x should be a vector of unit length (meaning length 1).