In [5]:
import numpy as np
A = np.array([[56.0, 0.0, 4.4, 68.0],
[1.2, 1.4, 52.0, 8.0],
[1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2   1.4  52.    8. ]
 [  1.8 135.   99.    0.9]]


In [8]:
# zero means false
cal= A.sum(axis=0)
print(cal)

[ 59.  136.4 155.4  76.9]


In [9]:
percentage= 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831  1.02639296 33.46203346 10.40312094]
 [ 3.05084746 98.97360704 63.70656371  1.17035111]]
